apiVersion: devopstoolkitseries.com/v1alpha1
kind: GitOpsClaim
metadata:
  name: a-team-gitops
spec:
  id: a-team-gitops
  compositionSelector:
    matchLabels:
      provider: argo
  parameters:
    kubeConfig:
      secretName: a-team-eks-ekscluster
      secretNamespace: crossplane-system
    gitOpsRepo: https://github.com/vfarcic/devops-toolkit-crossplane.git
