customPlaybooks:
- triggers:
  - on_deployment_update:
      namespace_prefix: production
  actions:
  - resource_babysitter:
      omitted_fields: []
      fields_to_monitor:
      - spec.template.spec.containers[].image
  sinks:
  - main_slack_sink
  - robusta_ui_sink
- triggers:
  - on_kubernetes_any_resource_all_changes: {}
  actions:
  - resource_babysitter: {}
  sinks:
  - main_slack_sink
  - robusta_ui_sink