customPlaybooks:
- triggers:
  - on_deployment_update:
      namespace_prefix: production
  actions:
  - resource_babysitter:
      omitted_fields: []
      fields_to_monitor:
      - spec.template.spec.containers[0].image
