customPlaybooks:
- triggers:
  - on_deployment_update:
      namespace_prefix: production
  actions:
  - resource_babysitter:
      omitted_fields: []
      fields_to_monitor:
      - spec.template.spec.containers[0].image
- triggers:
  - on_kubernetes_any_resource_all_changes:
      namespace_prefix: a-team
  actions:
  - resource_babysitter: {}
