customPlaybooks:
- triggers:
  - on_deployment_update:
      namespace_prefix: production
  actions:
  - resource_babysitter:
      omitted_fields: []
      fields_to_monitor:
      - spec.template.spec.containers[].image
- triggers:
  - on_schedule:
      fixed_delay_repeat:
        repeat: 5
        seconds_delay: 10
  actions:
  - http_stress_test:
      url: devops-toolkit.production
      n: 100
  